// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"
#include <widget/lv_ag_gif.h>
#include <esp_heap_caps.h>

// static const uint8_t *buffer = (uint8_t *)lv_mem_alloc(150 * 150 * 2);

void ui_ScreenMainGif_screen_init(void)
{
    ui_ScreenMainGif = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMainGif, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMainGif, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMainGif, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_add_event_cb(ui_ScreenMainGif, ui_event_ScreenMainGif, LV_EVENT_ALL, NULL);
    // Add logo gif
    heap_caps_print_heap_info(MALLOC_CAP_DEFAULT);
    LV_LOG_INFO("");
    ui_img_main_gif = lv_ag_gif_create(ui_ScreenMainGif);
    // lv_ag_gif_set_framebuf(ui_img_main_gif, (uint8_t *)buffer);
    // lv_ag_gif_set_src(ui_img_main_gif, "L:/voron.gif");
    lv_obj_align(ui_img_main_gif, LV_ALIGN_CENTER, 0, 0);
    heap_caps_print_heap_info(MALLOC_CAP_DEFAULT);
    LV_LOG_INFO("");
}
